--- #YAML:1.0
name:               Net-FreshBooks-API
version:            0.10
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Class::Accessor::Fast:  0
    Clone:                0
    Crypt::SSLeay:        0
    Data::Dump:           0
    Data::Dumper:         0
    DateTime:             0
    English:              0
    File::Slurp:          0
    File::Spec:           0
    Lingua::EN::Inflect:  0
    LWP::UserAgent:       0
    Path::Class:          0
    Sub::Override:        0
    Test::Exception:      0
    Test::More:           0
    Test::Pod:            0
    Test::Pod::Coverage:  0
    Test::WWW::Mechanize:  0
    Test::XML:            0
    URI:                  0
    XML::LibXML:          0
    XML::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
