---
abstract: 'Easy OO access to the FreshBooks.com API'
author:
  - 'Edmund von der Burg <evdb@ecclestoad.co.uk>'
  - 'Olaf Alders <olaf@wundercounter.com>'
build_requires:
  DateTime: 0
  English: 0
  File::Slurp: 0
  Module::Build: 0.3601
  Sub::Override: 0
  Test::Exception: 0
  Test::More: 0
  Test::WWW::Mechanize: 0
  Test::XML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-FreshBooks-API
requires:
  Carp: 0
  Clone: 0
  Data::Dump: 0
  LWP::UserAgent: 0
  Lingua::EN::Inflect: 0
  Moose: 0
  Moose::Role: 0
  Net::OAuth::Simple: 0
  Params::Validate: 0
  Path::Class: 0
  URI: 0
  WWW::Mechanize: 0
  XML::LibXML: 0
  XML::Simple: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-FreshBooks-API
  homepage: http://github.com/oalders/net-freshbooks-api/tree
  repository: git://github.com/oalders/net-freshbooks-api.git
version: 0.18
